#!/bin/bash
# MIT License - Copyright (c) 2026 ThierryN - https://github.com/ThierryN/fire-flow
#
# Auto-generate SKILLS-INDEX.md from GIT-TRACKED skills only.
# Run from the plugin root: bash scripts/generate-skills-index.sh
#
# IMPORTANT: This only indexes files tracked by git, NOT everything on disk.
# Private/project-specific skills that aren't git-added stay invisible.
# This prevents leaking private skill names (IRS, Stripe, Supabase, etc.)
# into the public repository.

set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SKILLS_DIR="$PLUGIN_ROOT/skills-library"
OUTPUT="$SKILLS_DIR/SKILLS-INDEX.md"

if [ ! -d "$SKILLS_DIR" ]; then
    echo "[ERROR] skills-library directory not found at $SKILLS_DIR"
    exit 1
fi

cd "$PLUGIN_ROOT"

# Get only git-tracked skill files (excludes private/untracked skills)
TRACKED_FILES=$(git ls-files skills-library/ | grep '\.md$' | grep -v 'SKILLS-INDEX.md' | sort)
TOTAL=$(echo "$TRACKED_FILES" | grep -c '.' || echo 0)

# Get version from plugin.json
VERSION=$(grep '"version"' "$PLUGIN_ROOT/plugin.json" | head -1 | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')

# Start generating the index
cat > "$OUTPUT" << HEADER
# Skills Library Index

> Auto-generated by \`scripts/generate-skills-index.sh\`
> Last updated: $(date +%Y-%m-%d)
> Plugin version: v${VERSION}
> **Only includes published (git-tracked) skills.**

## Summary

**Published skills: ${TOTAL}**

Additional project-specific skills can be added locally and will not appear in this index.

---

## Categories

HEADER

# Group tracked files by directory and generate entries
echo "$TRACKED_FILES" | while read -r file; do
    [ -z "$file" ] && continue
    # Get relative directory under skills-library/
    REL="${file#skills-library/}"
    echo "$REL"
done | while read -r rel; do
    # Extract directory path (everything before last /)
    DIR=$(dirname "$rel")
    echo "$DIR"
done | sort -u | while read -r category; do
    [ "$category" = "." ] && continue

    # Count files in this category
    COUNT=$(echo "$TRACKED_FILES" | grep "^skills-library/${category}/" | wc -l | tr -d ' ')
    [ "$COUNT" -eq 0 ] && continue

    # Format category name
    TITLE=$(echo "$category" | sed 's/\// > /g' | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')

    echo "### $TITLE ($COUNT skills)" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

    echo "$TRACKED_FILES" | grep "^skills-library/${category}/" | while read -r file; do
        SKILL_NAME=$(basename "$file" .md)
        DESC=$(grep -m 1 "^# " "$PLUGIN_ROOT/$file" 2>/dev/null | sed 's/^# //' || echo "$SKILL_NAME")
        echo "- \`$SKILL_NAME\` — $DESC" >> "$OUTPUT"
    done

    echo "" >> "$OUTPUT"
done

# Footer
cat >> "$OUTPUT" << FOOTER
---

*Generated automatically from git-tracked files only. Private skills on disk are excluded.*
*Run \`bash scripts/generate-skills-index.sh\` to regenerate.*
FOOTER

echo "=== SKILLS INDEX GENERATED ==="
echo "  Published skills: $TOTAL"
echo "  Output: $OUTPUT"
echo "  Version: v$VERSION"
echo "  (Private/untracked skills excluded)"
